name: Java CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up Java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Display AWS CLI Configuration
      run: aws configure list
      

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: target/
    - name: list target directory
      run: |
        ls -l target/

    - name: Upload to S3
      run: |
        aws s3 cp target/ s3://mycoderepo/SpringBootDev/ --recursive --debug

