name: Java CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up Java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install
    - name: Unset JAVA_HOME
      run: |
        unset JAVA_HOME

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: configure aws cli
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: target/*.jar

    - name: Upload to S3
      run: |
        aws s3 cp target/*.jar s3://mycoderepo/SpringBootDev/

